# Generated by Django 2.2 on 2019-04-23 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asientos', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('horario', models.TimeField()),
                ('pasajeros', models.ManyToManyField(through='pasaje.Asiento', to='pasaje.Pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('piloto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasaje.Chofer')),
                ('trayectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasaje.Trayecto')),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='pasajeros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasaje.Pasajero'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='trayectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasaje.Trayecto'),
        ),
    ]
