# Generated by Django 2.2 on 2019-04-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='asientos',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], unique=True),
        ),
    ]
