# Generated by Django 2.2 on 2019-04-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0003_auto_20190423_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='pasajeros',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='trayectos',
            field=models.ManyToManyField(through='pasaje.Asiento', to='pasaje.Trayecto'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='trayectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasaje.Trayecto'),
        ),
    ]
