# Generated by Django 2.2 on 2019-04-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0004_auto_20190423_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asientos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='trayectos',
        ),
        migrations.DeleteModel(
            name='Asiento',
        ),
        migrations.AddField(
            model_name='viaje',
            name='pasajeros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasaje.Pasajero'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='trayectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasaje.Trayecto'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='pasajeros',
            field=models.ManyToManyField(through='pasaje.Viaje', to='pasaje.Pasajero'),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('trayectos', 'asientos')},
        ),
    ]
