# Generated by Django 2.2 on 2019-04-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0006_auto_20190424_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
    ]
