# Generated by Django 2.2 on 2019-04-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0007_remove_viaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='asientos',
        ),
    ]
