# Generated by Django 2.2 on 2019-04-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0008_auto_20190424_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='horario',
        ),
    ]
